import { Bell, BookOpen, CalendarDays, CheckCircle2, ChevronRight, CircleHelp, Clock3, Download, FileText, FolderOpen, LayoutDashboard, LogOut, Menu, MessageSquare, Plus, Settings, ShieldCheck, Sparkles, User, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import Reveal from '../components/Reveal'

const initialTasks=[
  {id:1,title:'Review formation details',due:'Today',done:false},
  {id:2,title:'Confirm registered agent selection',due:'Tomorrow',done:false},
  {id:3,title:'Upload owner identification',due:'Jul 24',done:true},
  {id:4,title:'Review operating agreement request',due:'Jul 28',done:false}
]

export default function Dashboard(){
  const {user,logout,notify}=useApp(); const [mobile,setMobile]=useState(false); const [tasks,setTasks]=useState(initialTasks)
  const onboarding=useMemo(()=>{try{return JSON.parse(localStorage.getItem('abf-onboarding'))||{}}catch{return {}}},[])
  const business=onboarding.businessName||'Your New Business'; const state=onboarding.state||'Wyoming'
  const toggleTask=id=>setTasks(v=>v.map(t=>t.id===id?{...t,done:!t.done}:t))
  return <section className="dashboard-page"><aside className={mobile?'open':''}><div className="dash-brand"><span>ABF</span><strong>American Business<br/>Formations</strong><button onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div><nav><a className="active" href="#overview"><LayoutDashboard/>Overview</a><a href="#orders"><FolderOpen/>Orders & services</a><a href="#documents"><FileText/>Documents</a><a href="#messages"><MessageSquare/>Messages <b>2</b></a><a href="#calendar"><CalendarDays/>Compliance calendar</a><a href="#resources"><BookOpen/>Resources</a></nav><div className="dash-help"><CircleHelp/><strong>Need help?</strong><p>Contact the support team or open the on-site guide.</p><Link to="/contact">Get support</Link></div><nav className="dash-bottom"><a href="#settings"><Settings/>Settings</a><button onClick={logout}><LogOut/>Log out</button></nav></aside><main><header><button className="dash-mobile-menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div><span>Client dashboard</span><h1>Good evening, {user?.name?.split(' ')[0]||'Founder'}.</h1></div><div className="dash-head-actions"><button aria-label="Notifications, 3 unread"><Bell/><i>3</i></button><div className="user-chip"><div>{(user?.name||'F')[0].toUpperCase()}</div><span><strong>{user?.name||'Founder Account'}</strong><small>{user?.email||'founder@example.com'}</small></span></div></div></header><div className="dash-content">
    <Reveal as="section" delay={0} className="business-summary"><div><span className="status-pill"><Clock3/> Formation in progress</span><h2>{business}</h2><p>{onboarding.entityType||'LLC'} • {state} • {onboarding.industry||'Professional Services'}</p></div><div className="progress-ring"><svg viewBox="0 0 42 42"><circle cx="21" cy="21" r="16"/><circle className="progress" cx="21" cy="21" r="16"/></svg><strong>62%</strong></div><div className="summary-action"><small>Current stage</small><strong>Information review</strong><span>Estimated next update: 1–2 business days</span><button onClick={()=>notify('Formation details opened in demo mode.')}>View details <ChevronRight/></button></div></Reveal>
    <div className="dash-grid"><Reveal as="section" delay={1} className="dash-card task-card"><div className="dash-card-head"><div><span>Your next steps</span><h3>Formation checklist</h3></div><button><Plus/> Add task</button></div><div className="task-list">{tasks.map(task=><label key={task.id} className={task.done?'done':''}><input type="checkbox" checked={task.done} onChange={()=>toggleTask(task.id)}/><i>{task.done&&<CheckCircle2/>}</i><span><strong>{task.title}</strong><small>Due {task.due}</small></span><ChevronRight/></label>)}</div></Reveal><Reveal as="section" delay={2} className="dash-card guide-card"><div className="guide-icon"><Sparkles/></div><span>ABF Guide</span><h3>What should I focus on next?</h3><p>Your ownership details are complete. Review the registered-agent selection and confirm the mailing address before the next milestone.</p><div><button>Explain registered agents</button><button>Show missing information</button></div></Reveal></div>
    <div className="dash-grid lower"><Reveal as="section" delay={0} className="dash-card" id="documents"><div className="dash-card-head"><div><span>Documents</span><h3>Recent files</h3></div><button>View all</button></div><div className="document-list">{[['Formation summary','PDF','Updated Jul 20'],['Owner information checklist','PDF','Updated Jul 19'],['Service selection receipt','PDF','Updated Jul 18']].map(([name,type,date])=><div key={name}><div className="doc-icon"><FileText/></div><span><strong>{name}</strong><small>{type} • {date}</small></span><button aria-label="Download document"><Download/></button></div>)}</div></Reveal><Reveal as="section" delay={1} className="dash-card"><div className="dash-card-head"><div><span>Recommended</span><h3>Complete your business setup</h3></div></div><div className="recommend-list"><Link to="/ein"><div><ShieldCheck/></div><span><strong>Apply for an EIN</strong><small>Prepare for taxes, banking, and hiring.</small></span><ChevronRight/></Link><Link to="/business-banking"><div><FileText/></div><span><strong>Business banking</strong><small>Separate personal and business finances.</small></span><ChevronRight/></Link><Link to="/website-builder"><div><User/></div><span><strong>Build your online presence</strong><small>Plan a website, domain, and email.</small></span><ChevronRight/></Link></div></Reveal></div>
    <Reveal as="section" className="dash-card timeline-card"><div className="dash-card-head"><div><span>Formation progress</span><h3>Milestone timeline</h3></div><button>View service order</button></div><div className="timeline"><div className="complete"><i><CheckCircle2/></i><span><strong>Formation plan created</strong><small>July 18, 2026</small></span></div><div className="complete"><i><CheckCircle2/></i><span><strong>Business information submitted</strong><small>July 19, 2026</small></span></div><div className="current"><i><Clock3/></i><span><strong>Information review</strong><small>In progress</small></span></div><div><i>4</i><span><strong>State filing</strong><small>Upcoming</small></span></div><div><i>5</i><span><strong>Formation complete</strong><small>Upcoming</small></span></div></div></Reveal>
  </div></main></section>}
