import { ArrowLeft, ArrowRight, Building2, Check, MapPin, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { states, stateFeeSamples } from '../data/states'
import { api, withLocalFallback } from '../lib/api'
import { useApp } from '../context/AppContext'

const steps=['Business basics','Formation state','Ownership','Services','Review']
export default function Onboarding(){
  const {selectedState,setSelectedState,user,notify}=useApp();const navigate=useNavigate();const [step,setStep]=useState(0);const [loading,setLoading]=useState(false)
  const [form,setForm]=useState({businessName:'',industry:'',description:'',state:selectedState||'',entityType:'LLC',owners:'1',management:'Member-managed',services:['LLC Formation'],email:user?.email||''})
  const set=(key,value)=>setForm(v=>({...v,[key]:value}));const toggle=service=>setForm(v=>({...v,services:v.services.includes(service)?v.services.filter(x=>x!==service):[...v.services,service]}))
  const canNext=useMemo(()=>step===0?form.businessName&&form.industry:step===1?form.state:step===2?form.owners:true,[step,form])
  const finish=async()=>{setLoading(true);localStorage.setItem('abf-onboarding',JSON.stringify(form));await withLocalFallback(()=>api.submitOnboarding(form),()=>({ok:true}));setSelectedState(form.state);notify('Your business plan has been saved.');setLoading(false);navigate(user?'/dashboard':'/signup')}
  return <section className="onboarding-page"><div className="onboarding-shell"><aside><div className="onboarding-brand"><span>ABF</span><strong>American Business<br/>Formations</strong></div><h2>Let’s build your formation plan.</h2><p>Your answers save automatically in this demo after completion.</p><ol>{steps.map((label,i)=><li key={label} className={i===step?'active':i<step?'done':''}><span>{i<step?<Check/>:i+1}</span>{label}</li>)}</ol><small>General information only. This workflow is not legal or tax advice.</small></aside><main><div className="onboarding-progress"><span>Step {step+1} of {steps.length}</span><div><i style={{width:`${((step+1)/steps.length)*100}%`}}></i></div></div>
    {step===0&&<div key={step} className="step-panel"><Building2 className="step-icon"/><span>Business basics</span><h1>Tell us about your new business</h1><p>Start with the name and a simple description. You can update these details later.</p><label>Preferred business name<input value={form.businessName} onChange={e=>set('businessName',e.target.value)} placeholder="Example: North Ridge Consulting"/></label><label>Industry<select value={form.industry} onChange={e=>set('industry',e.target.value)}><option value="">Choose an industry</option><option>Professional Services</option><option>Ecommerce</option><option>Technology</option><option>Construction</option><option>Food & Hospitality</option><option>Health & Wellness</option><option>Creative Services</option><option>Other</option></select></label><label>What will the business do?<textarea value={form.description} onChange={e=>set('description',e.target.value)} rows="4" placeholder="Briefly describe the products or services..."></textarea></label></div>}
    {step===1&&<div key={step} className="step-panel"><MapPin className="step-icon"/><span>Formation state</span><h1>Where will you form the business?</h1><p>Most founders form in the state where they primarily operate. Professional advice may be appropriate for multi-state or non-resident situations.</p><div className="state-choice-grid">{['Wyoming','Delaware','Texas','Florida'].map(x=><button className={form.state===x?'selected':''} onClick={()=>set('state',x)} key={x}><strong>{x}</strong><small>Sample state fee: ${stateFeeSamples[x]||'varies'}</small></button>)}</div><label>Or choose another state<select value={form.state} onChange={e=>set('state',e.target.value)}><option value="">Select a state</option>{states.map(x=><option key={x}>{x}</option>)}</select></label><label>Entity type<select value={form.entityType} onChange={e=>set('entityType',e.target.value)}><option>LLC</option><option>C Corporation</option><option>Nonprofit Corporation</option></select></label></div>}
    {step===2&&<div key={step} className="step-panel"><Users className="step-icon"/><span>Ownership</span><h1>How will the business be owned?</h1><p>These answers shape the company profile and document checklist.</p><label>Number of owners or members<select value={form.owners} onChange={e=>set('owners',e.target.value)}><option>1</option><option>2</option><option>3</option><option>4+</option></select></label><div className="radio-cards"><button className={form.management==='Member-managed'?'selected':''} onClick={()=>set('management','Member-managed')}><strong>Member-managed</strong><span>Owners participate in day-to-day decisions.</span></button><button className={form.management==='Manager-managed'?'selected':''} onClick={()=>set('management','Manager-managed')}><strong>Manager-managed</strong><span>Selected managers handle operations.</span></button></div><label>Primary contact email<input value={form.email} type="email" onChange={e=>set('email',e.target.value)} placeholder="owner@example.com"/></label></div>}
    {step===3&&<div key={step} className="step-panel"><span>Recommended services</span><h1>What would you like help with?</h1><p>Select any services to include in the project summary. Live prices can be connected later.</p><div className="service-choice-grid">{['LLC Formation','Registered Agent','EIN','Operating Agreement','Licenses & Permits','Trademark','Business Banking','Website & Domain'].map(x=><button key={x} className={form.services.includes(x)?'selected':''} onClick={()=>toggle(x)}><span>{form.services.includes(x)?<Check/>:'+'}</span><strong>{x}</strong></button>)}</div></div>}
    {step===4&&<div key={step} className="step-panel review-panel"><span>Review your plan</span><h1>Confirm your business details</h1><p>Your completed summary will appear in the client dashboard.</p><div className="review-card"><div><small>Business name</small><strong>{form.businessName}</strong></div><div><small>Industry</small><strong>{form.industry}</strong></div><div><small>Formation</small><strong>{form.entityType} in {form.state}</strong></div><div><small>Ownership</small><strong>{form.owners} owner(s), {form.management}</strong></div><div className="full"><small>Selected services</small><div className="tag-row">{form.services.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="summary-price"><span>Service plan estimate</span><strong>$199</strong><small>+ {form.state} filing fee and selected add-ons</small></div></div>}
    <div className="onboarding-actions">{step>0?<button className="btn btn-ghost" onClick={()=>setStep(step-1)}><ArrowLeft/> Back</button>:<span/>}{step<steps.length-1?<button className="btn btn-primary" disabled={!canNext} onClick={()=>setStep(step+1)}>Continue <ArrowRight/></button>:<button className="btn btn-primary" disabled={loading} onClick={finish}>{loading?'Saving...':'Save formation plan'} <ArrowRight/></button>}</div></main></div></section>
}
