import { Eye, EyeOff, LockKeyhole, Loader2, Mail, User } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, withLocalFallback } from '../lib/api'
import { useApp } from '../context/AppContext'
import SEO from '../components/SEO'

export default function Signup(){
  const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const {login,notify}=useApp();const navigate=useNavigate()
  const submit=async e=>{e.preventDefault();setLoading(true);const payload=Object.fromEntries(new FormData(e.currentTarget));const role=payload.is_admin?'admin':'customer';const result=await withLocalFallback(()=>api.signup(payload),()=>({user:{name:payload.name,email:payload.email,role}}));login(result.user);notify('Account created successfully.');setLoading(false);navigate(role==='admin'?'/admin':'/start')}
  return <><SEO title="Create Account" description="Create your American Business Formations account." path="/signup" noindex /><section className="auth-page"><div className="auth-shell"><div className="auth-side signup-side"><div><span>Build with confidence</span><h1>Create one account for every business step.</h1><p>Save onboarding progress, store service requests, and return to your dashboard at any time.</p></div><img src="/illustrations/hero-business.svg" alt="Business formation illustration"/></div><div className="auth-form-wrap"><Link className="auth-back" to="/">← Back to website</Link><form className="auth-form" onSubmit={submit}><span>Get started</span><h2>Create your account</h2><p>This demo stores your session locally when Flask is not running.</p><label>Full name<div className="input-icon"><User/><input required name="name" placeholder="Your full name"/></div></label><label>Email address<div className="input-icon"><Mail/><input required type="email" name="email" placeholder="you@example.com"/></div></label><label>Password<div className="input-icon"><LockKeyhole/><input required minLength="6" type={show?'text':'password'} name="password" placeholder="At least 6 characters"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff/>:<Eye/>}</button></div></label><label className="check-control terms-check"><input required type="checkbox"/> I agree to the Terms, Privacy Policy, and service disclaimer.</label><label className="check-control terms-check"><input type="checkbox" name="is_admin"/> This is a demo admin account (for testing the admin portal only)</label><button className="btn btn-primary btn-block" disabled={loading}>{loading&&<Loader2 className="spin" size={18}/>}{loading?'Creating account...':'Create account'}</button><p className="auth-switch">Already have an account? <Link to="/login">Log in</Link></p></form></div></div></section></>
}
