import { useEffect, useMemo, useState } from 'react'
import { FolderCheck, ShieldCheck, Info, Phone, Mail, ExternalLink } from 'lucide-react'
import { api } from '../../../lib/api'
import { getState } from '../../../data/states'
import { computeDocumentRequirements, isUploadCard } from '../../../lib/documentRequirements'
import DocumentCard from '../../../components/ui/DocumentCard'
import Badge from '../../../components/ui/Badge'

// Matches the backend's real enforced cap (MAX_CONTENT_LENGTH in
// server/config.py) shown to the customer up front rather than letting a
// larger file pass client-side validation only to be rejected by the
// server (Part 10: never rely on frontend validation alone, but also never
// contradict it).
const MAX_SIZE_MB = 10

export default function DocumentsStep({ wizard }) {
  const { form, businessId, user, setStep } = wizard
  const selectedState = getState(form.state)

  const { generated, required, conditional, formationDocumentName } = useMemo(() => computeDocumentRequirements(form), [form])
  const uploadItems = useMemo(() => [...required, ...conditional].filter(isUploadCard), [required, conditional])

  const [existingDocs, setExistingDocs] = useState([])
  const [docsLoading, setDocsLoading] = useState(false)
  const [uploadState, setUploadState] = useState({}) // documentType -> { uploading, progress, error }
  const canUpload = Boolean(user && businessId)

  useEffect(() => {
    if (!canUpload) return
    let cancelled = false
    setDocsLoading(true)
    api.listDocuments(businessId)
      .then(result => { if (!cancelled) setExistingDocs(result?.data || []) })
      .catch(() => { if (!cancelled) setExistingDocs([]) })
      .finally(() => { if (!cancelled) setDocsLoading(false) })
    return () => { cancelled = true }
  }, [canUpload, businessId])

  const findDoc = (documentType) => existingDocs.find(d => d.document_type === documentType)

  const handleUpload = async (item, file) => {
    if (!canUpload) return
    setUploadState(s => ({ ...s, [item.documentType]: { uploading: true, progress: null, error: '' } }))
    try {
      const formData = new FormData()
      formData.append('file', file)
      formData.append('document_type', item.documentType)
      const result = await api.uploadDocument(`/documents/${businessId}/upload`, formData)
      setExistingDocs(docs => [result.data, ...docs.filter(d => d.document_type !== item.documentType)])
      setUploadState(s => ({ ...s, [item.documentType]: { uploading: false, progress: 100, error: '' } }))
    } catch (err) {
      setUploadState(s => ({ ...s, [item.documentType]: { uploading: false, progress: null, error: err?.message || 'Upload failed. Please try again.' } }))
    }
  }

  const handleRemove = async (item) => {
    const doc = findDoc(item.documentType)
    if (!doc || !canUpload) return
    try {
      await api.deleteDocument(businessId, doc.id)
      setExistingDocs(docs => docs.filter(d => d.id !== doc.id))
    } catch (err) {
      setUploadState(s => ({ ...s, [item.documentType]: { uploading: false, progress: null, error: err?.message || 'We could not remove this file. Please try again.' } }))
    }
  }

  const completedCount = uploadItems.filter(item => findDoc(item.documentType)).length
  const totalCount = uploadItems.length

  return (
    <div className="step-panel documents-step">
      <FolderCheck className="step-icon" /><span>Documents &amp; verification</span>
      <h1>Documents for your {selectedState?.name || 'formation'} LLC</h1>
      <p className="onboarding-note"><Info size={15} /> Document and filing requirements vary by state and by your business circumstances. We show only the items currently needed based on what you’ve selected so far this is general information, not legal advice.</p>

      {totalCount === 0 ? (
        <p className="documents-progress-empty"><ShieldCheck size={16} /> No document uploads are currently required based on the information you’ve provided.</p>
      ) : (
        <p className="documents-progress" aria-live="polite">{completedCount} of {totalCount} document item{totalCount === 1 ? '' : 's'} completed</p>
      )}

      {!canUpload && totalCount > 0 && (
        <p className="documents-signin-note">
          <Info size={15} /> You’ll create your free account in a later step. Once you do, you can come back here (or upload from your dashboard afterward) to securely add these files we never accept document uploads before a formation record exists for them.
        </p>
      )}

      <section aria-labelledby="docs-generated-heading">
        <h3 id="docs-generated-heading">Prepared for you</h3>
        <p className="documents-section-hint">Your {formationDocumentName || 'LLC formation document'} and related paperwork are generated by American Business Formations from your answers in this wizard nothing to upload.</p>
        <div className="document-card-grid">
          {generated.map(doc => (
            <DocumentCard
              key={doc.id}
              title={doc.label}
              officialName={doc.id === 'formation-document' ? doc.officialName : undefined}
              requirementType="generated"
              status="preparing"
              description={doc.description}
              generatedBy={doc.generatedBy}
            />
          ))}
          <DocumentCard
            title="Registered Agent Consent"
            requirementType="generated"
            status={form.registeredAgentConsent ? 'approved' : 'not_started'}
            description="Captured electronically on the Registered Agent step of this wizard a typed signature, signer name, and timestamp, kept on file. Not a document you need to upload."
            generatedBy="You, electronically"
          />
        </div>
      </section>

      {uploadItems.length > 0 && (
        <section aria-labelledby="docs-upload-heading">
          <h3 id="docs-upload-heading">Documents to provide</h3>
          <div className="document-card-grid">
            {uploadItems.map(item => {
              const doc = findDoc(item.documentType)
              const state = uploadState[item.documentType] || {}
              return (
                <DocumentCard
                  key={item.id}
                  title={item.label}
                  requirementType={item.requirementType}
                  status={doc ? 'uploaded' : 'not_started'}
                  description={item.description}
                  acceptedFormats={item.acceptedFormats}
                  maxSizeMb={item.maxSizeMb || MAX_SIZE_MB}
                  file={doc ? { name: doc.file_name, size: doc.size_bytes } : null}
                  uploading={state.uploading}
                  progress={state.progress}
                  uploadError={state.error}
                  disabled={!canUpload}
                  disabledReason="Available once your account is created you can add this from your dashboard afterward."
                  onUpload={(file) => handleUpload(item, file)}
                  onRemove={() => handleRemove(item)}
                />
              )
            })}
          </div>
        </section>
      )}

      <section aria-labelledby="docs-collected-heading" className="documents-collected-summary">
        <h3 id="docs-collected-heading">Already on file from your application</h3>
        <p className="documents-section-hint">Business name, business purpose, addresses, ownership, registered agent, and organizer details are collected as structured answers earlier in this wizard you never need to upload these as documents.</p>
      </section>

      <div className="documents-support-card">
        <div className="documents-support-icon"><Phone size={20} aria-hidden="true" /></div>
        <div>
          <h4>Need Help? Our Team Is Here.</h4>
          <p>Our support team may contact you by phone or email if any required information or documents are missing, incomplete, or need clarification. Please keep your contact details current so we can help keep your filing moving.</p>
          {form.email || form.phone ? (
            <p className="documents-support-contact">
              {form.email && <span><Mail size={14} aria-hidden="true" /> {form.email}</span>}
              {form.phone && <span><Phone size={14} aria-hidden="true" /> {form.phone}</span>}
              <button type="button" className="btn-link" onClick={() => setStep(2)}>Update Contact Information <ExternalLink size={12} /></button>
            </p>
          ) : (
            <button type="button" className="btn btn-outline btn-sm" onClick={() => setStep(2)}>Add Contact Information</button>
          )}
        </div>
      </div>
      {docsLoading && <p className="sr-only" role="status">Loading your documents…</p>}
    </div>
  )
}
