import { Link } from 'react-router-dom'
import { FileText, ShieldCheck, FileCheck2, Sparkles } from 'lucide-react'
import { fieldAria } from '../../../lib/formErrors'
import { priceToNumber } from '../useOnboardingWizard'
import { STATE_FEE_DISCLAIMER } from '../../../data/states'
import { getStateRequirements } from '../../../config/stateRequirements'

export default function ReviewStep({ wizard }) {
  const { form, set, errors, handleFieldChange, fieldRefs, addOnCatalog, selectedPlan, stateFee, selectedState, setStep } = wizard
  const requirements = getStateRequirements(form.state)
  const formationDocumentName = requirements?.formationDocumentName || 'LLC Formation Document'

  const selectedAddOns = form.addOns.map(id => addOnCatalog.find(a => a.id === id)).filter(Boolean)
  const estimatedTotal = priceToNumber(selectedPlan.price) + stateFee + selectedAddOns.reduce((s, a) => s + a.price, 0)
  const planRenews = /per year/i.test(selectedPlan.note)
  const recurringAddOns = selectedAddOns.filter(a => a.recurring)

  const handleReviewAcknowledge = (checked) => {
    set('formationReviewApproved', checked)
    set('formationReviewApprovedAt', checked ? new Date().toISOString() : '')
    if (checked) set('formationReviewVersion', (form.formationReviewVersion || 0) + 1)
  }

  return (
    <div className="step-panel review-panel">
      <FileText className="step-icon" /><span>Review your plan</span>
      <h1>Confirm your LLC details</h1>

      <div className="generated-document-preview">
        <div className="generated-document-preview-head">
          <Sparkles size={18} aria-hidden="true" />
          <div>
            <strong>{formationDocumentName}</strong>
            <span>Generated by American Business Formations from your answers below filed as your {selectedState?.name || form.state} LLC Formation Document.</span>
          </div>
        </div>
        <div className="review-card">
          <div><small>Business name</small><strong>{form.businessName}</strong></div>
          <div><small>Formation state</small><strong>{selectedState?.name || form.state}</strong></div>
          <div><small>Entity</small><strong>{form.entityType}</strong></div>
          <div><small>Business purpose</small><strong>{form.purpose || '—'}</strong></div>
          <div><small>Principal address</small><strong>{form.principalLine1 ? `${form.principalLine1}, ${form.principalCity}, ${selectedState?.code || form.state} ${form.principalZip}` : '—'}</strong></div>
          <div><small>Ownership</small><strong>{form.owners} owner(s), {form.management}</strong></div>
          <div><small>Registered agent</small><strong>{form.registeredAgentType === 'abf' ? 'American Business Formations' : form.registeredAgentName || 'Self / other'}</strong></div>
          <div><small>Organizer</small><strong>{form.organizerType === 'self' ? 'Self' : form.organizerName}</strong></div>
          <div><small>Effective date</small><strong>{form.effectiveDateOption === 'filing' ? 'Upon filing' : form.effectiveDate || 'Delayed'}</strong></div>
        </div>
        <p className="generated-document-preview-note">See something that needs to change? Go back to the relevant step to correct it <button type="button" className="btn-link" onClick={() => setStep(1)}>Business basics</button>, <button type="button" className="btn-link" onClick={() => setStep(3)}>address</button>, <button type="button" className="btn-link" onClick={() => setStep(4)}>ownership</button>, or <button type="button" className="btn-link" onClick={() => setStep(5)}>registered agent</button>.</p>
        <label className="check-control terms-check">
          <input type="checkbox" checked={form.formationReviewApproved} onChange={e => handleReviewAcknowledge(e.target.checked)} ref={el => fieldRefs.current.formationReviewApproved = el} {...fieldAria('formationReviewApproved-error', errors.formationReviewApproved)} /> <FileCheck2 size={14} style={{ verticalAlign: '-2px', marginRight: 4 }} aria-hidden="true" />I confirm that the information above is accurate and may be used to prepare my LLC formation filing.
        </label>
        {errors.formationReviewApproved && <p id="formationReviewApproved-error" className="field-error">{errors.formationReviewApproved}</p>}
      </div>

      <div className="review-card">
        <div><small>Plan</small><strong>{selectedPlan.name} {selectedPlan.price} {selectedPlan.note}</strong></div>
        <div className="full"><small>Selected add-ons</small><div className="tag-row">{form.addOns.length ? form.addOns.map(id => <span key={id}>{addOnCatalog.find(a => a.id === id)?.name}</span>) : <span>None selected</span>}</div></div>
      </div>
      <div className="order-breakdown">
        <div><span>Service plan ({selectedPlan.name})</span><strong>${priceToNumber(selectedPlan.price)}</strong></div>
        <div><span>{selectedState?.name || 'State'} state filing fee <em>(one-time government fee)</em></span><strong>${stateFee}</strong></div>
        {selectedAddOns.map(a => <div key={a.id}><span>{a.name}{a.recurring ? ` (${a.recurring})` : ''}</span><strong>${a.price}</strong></div>)}
        <div className="order-total"><span>Order total</span><strong>${estimatedTotal}</strong></div>
        {(planRenews || recurringAddOns.length > 0) && <div className="order-renewal">
          <span>Then renews</span>
          <strong>
            {planRenews && `${selectedPlan.price}/year (${selectedPlan.name} plan)`}
            {planRenews && recurringAddOns.length > 0 && ' + '}
            {recurringAddOns.map((a, i) => <span key={a.id}>{i > 0 && ' + '}${a.price}/{/month/i.test(a.recurring) ? 'month' : 'year'} ({a.name})</span>)}
          </strong>
        </div>}
      </div>
      <p className="onboarding-note"><ShieldCheck size={15} /> {STATE_FEE_DISCLAIMER} Your final total is calculated by our server when you submit.</p>
      <label className="check-control terms-check">
        <input type="checkbox" checked={form.finalTermsAccepted} onChange={e => handleFieldChange('finalTermsAccepted', e.target.checked)} ref={el => fieldRefs.current.finalTermsAccepted = el} {...fieldAria('finalTermsAccepted-error', errors.finalTermsAccepted)} /> I agree to the Terms of Service, recurring billing terms, and <Link to="/refund-policy" target="_blank" rel="noopener noreferrer">refund and cancellation policy</Link>.
      </label>
      {errors.finalTermsAccepted && <p id="finalTermsAccepted-error" className="field-error">{errors.finalTermsAccepted}</p>}
    </div>
  )
}
