import { ArrowRight, Check, Download, LayoutTemplate, Palette, RefreshCw, Sparkles, Type, WandSparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import Reveal from '../../components/Reveal'

const palettes=[['#172A46','#315F9D','#D7A548','#F8F5EE'],['#111827','#0F766E','#F59E0B','#F8FAFC'],['#312E81','#7C3AED','#EC4899','#FFF7ED'],['#1F2937','#B45309','#FDE68A','#FFFBEB']]
export default function BrandStudio(){
  const [name,setName]=useState('American Venture'); const [tagline,setTagline]=useState('Built to move business forward'); const [palette,setPalette]=useState(0); const [mark,setMark]=useState('AV')
  const logo=useMemo(()=>name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()||'AB',[name])
  return <div className="studio-page brand-studio"><Reveal as="section" className="studio-welcome compact"><div><span>Brand studio</span><h1>Create a clear, professional identity.</h1><p>Use guided tools to explore a logo direction, colors, typography, and practical brand assets.</p></div><button className="studio-primary" onClick={()=>setMark(logo)}><WandSparkles/> Generate direction</button></Reveal><div className="brand-builder-grid"><section className="brand-controls studio-panel"><div className="panel-heading"><div><span>Brand details</span><h3>Shape your direction</h3></div></div><label>Business name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Tagline<input value={tagline} onChange={e=>setTagline(e.target.value)}/></label><label>Logo initials<input maxLength="3" value={mark} onChange={e=>setMark(e.target.value.toUpperCase())}/></label><div className="brand-label">Color direction</div><div className="palette-choices">{palettes.map((p,i)=><button className={palette===i?'active':''} key={i} onClick={()=>setPalette(i)}>{p.map(c=><i key={c} style={{background:c}}/>)}{palette===i&&<span><Check/></span>}</button>)}</div><button className="shuffle-button" onClick={()=>setPalette((palette+1)%palettes.length)}><RefreshCw/> Try another palette</button></section><section className="brand-preview" style={{'--brand-primary':palettes[palette][0],'--brand-secondary':palettes[palette][1],'--brand-accent':palettes[palette][2],'--brand-soft':palettes[palette][3]}}><div className="brand-preview-top"><span>Live preview</span><button><Download/> Export demo</button></div><div className="logo-canvas"><div className="generated-logo">{mark||logo}</div><h2>{name}</h2><p>{tagline}</p></div><div className="brand-asset-row"><div><span className="mini-logo">{mark||logo}</span><small>App icon</small></div><div className="brand-card-mock"><b>{mark||logo}</b><span>{name}<small>{tagline}</small></span></div><div className="brand-social-mock"><Sparkles/><strong>{name}</strong><small>Launch your next chapter.</small></div></div></section></div><section className="brand-tools"><article><Palette/><h3>Color system</h3><p>Build accessible primary, secondary, and supporting colors.</p></article><article><Type/><h3>Typography</h3><p>Choose a practical headline and body font pairing.</p></article><article><LayoutTemplate/><h3>Brand templates</h3><p>Prepare social, card, and document design directions.</p></article><article><Sparkles/><h3>AI brand voice</h3><p>Generate a tone guide based on your audience and goals.</p><Link to="/studio/ai-tools">Open AI tool <ArrowRight/></Link></article></section></div>
}
