import { ArrowRight, BadgeCheck, Banknote, BookOpenCheck, Building2, CalendarClock, Check, ChevronRight, CircleDollarSign, ClipboardList, FileCheck2, FileText, Landmark, LockKeyhole, MapPinCheck, ReceiptText, ShieldCheck, Sparkles, Store, Upload, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import Reveal from '../../components/Reveal'

const sections={
  business:{icon:Building2,kicker:'Company profile',title:'Everything about your business, organized.',copy:'Keep ownership, addresses, contacts, and company records accurate in one secure workspace.',stats:[['Profile completeness','82%'],['Business contacts','2'],['Saved addresses','1']],cards:[['Company information','Review your legal name, entity type, industry, and business purpose.',Building2],['Owners & managers','Manage ownership, roles, and decision-making structure.',Users],['Business addresses','Keep principal, mailing, and registered office details together.',MapPinCheck],['Records vault','Store company resolutions, agreements, and important records.',LockKeyhole]]},
  formation:{icon:FileCheck2,kicker:'Formation center',title:'Make your business official with confidence.',copy:'Follow a clear filing roadmap, review details, and keep every formation document in one place.',stats:[['Formation progress','68%'],['Open tasks','3'],['Estimated review','1–2 days']],cards:[['Formation order','Review your company details and selected filing package.',ClipboardList],['Registered agent','Confirm the official contact for state correspondence.',ShieldCheck],['EIN application','Prepare the details needed for your federal tax ID.',BadgeCheck],['Operating agreement','Build the internal rules for ownership and management.',FileText]]},
  compliance:{icon:ShieldCheck,kicker:'Compliance center',title:'Stay ready for every deadline.',copy:'Track reports, licenses, permits, renewals, and company records without relying on scattered reminders.',stats:[['Compliance score','Good'],['Upcoming deadlines','2'],['Active licenses','0']],cards:[['Annual report','See your next state filing date and preparation checklist.',CalendarClock],['Licenses & permits','Build a location and industry-based permit checklist.',MapPinCheck],['Compliance calendar','See deadlines, renewals, and recurring tasks.',CalendarClock],['Company records','Keep minutes, resolutions, and amendments organized.',BookOpenCheck]]},
  finance:{icon:CircleDollarSign,kicker:'Finance & operations',title:'Build a stronger financial foundation.',copy:'Prepare for banking, invoicing, bookkeeping, funding, and tax responsibilities from one workspace.',stats:[['Finance setup','25%'],['Open invoices','$0'],['Funding matches','12']],cards:[['Business banking','Prepare documents and compare account requirements.',Landmark],['Invoices & payments','Create branded invoices and track payment status.',ReceiptText],['Bookkeeping setup','Organize expense categories and monthly routines.',BookOpenCheck],['Funding finder','Explore sample grants, loans, and business programs.',Banknote]]}
}

export default function StudioSection({section}){
  const s=sections[section]||sections.business; const Icon=s.icon
  return <div className="studio-page section-dashboard"><Reveal as="section" className="section-dashboard-hero"><div><span>{s.kicker}</span><h1>{s.title}</h1><p>{s.copy}</p></div><i><Icon/></i></Reveal><section className="section-stat-grid">{s.stats.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</section><section className="section-card-grid">{s.cards.map(([title,copy,CardIcon],i)=><article key={title}><div className="section-card-top"><i><CardIcon/></i>{i===0&&<span>Recommended</span>}</div><h3>{title}</h3><p>{copy}</p><button onClick={()=>{}}>Open tool <ArrowRight/></button></article>)}</section><section className="section-assistant"><div><Sparkles/></div><span><strong>Need a personalized explanation?</strong><small>Formation AI can explain any task and turn it into a simple action plan.</small></span><Link to="/studio/ai-tools">Ask Formation AI <ChevronRight/></Link></section></div>
}
