import { useRef } from 'react'
import { FileCheck2, FileText, RefreshCw, Trash2, CheckCircle2, AlertTriangle, Clock, Sparkles, Lock } from 'lucide-react'
import Badge from './Badge'
import FileDropzone from './FileDropzone'

const REQUIREMENT_BADGE = {
  required: { variant: 'danger', label: 'Required' },
  conditional: { variant: 'warning', label: 'Conditional' },
  optional: { variant: 'neutral', label: 'Optional' },
  generated: { variant: 'success', label: 'Generated by Us' },
}

const STATUS_META = {
  not_started: { label: 'Not Started', icon: Clock, variant: 'neutral' },
  uploaded: { label: 'Uploaded', icon: FileCheck2, variant: 'success' },
  received: { label: 'Received', icon: FileCheck2, variant: 'success' },
  under_review: { label: 'Under Review', icon: Clock, variant: 'warning' },
  approved: { label: 'Approved', icon: CheckCircle2, variant: 'success' },
  needs_attention: { label: 'Needs Attention', icon: AlertTriangle, variant: 'danger' },
  not_required: { label: 'Not Required', icon: CheckCircle2, variant: 'neutral' },
  preparing: { label: 'Preparing', icon: Sparkles, variant: 'neutral' },
}

function formatSize(bytes) {
  if (!bytes && bytes !== 0) return ''
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

// A single document requirement rendered as a card used for all three
// categories (Part 5/8): a generated document (read-only, Category B), or
// a customer upload slot, required/conditional/optional (Category C).
// Category A (structured intake fields) intentionally has no card of its
// own here DocumentsStep.jsx summarizes those separately instead of
// turning ordinary form fields into fake upload requirements.
export default function DocumentCard({
  title, officialName, requirementType = 'optional', status = 'not_started',
  description, acceptedFormats = ['PDF', 'JPG', 'PNG'], maxSizeMb = 10,
  file, uploading = false, progress = null, uploadError,
  onUpload, onRemove, disabled = false, disabledReason,
  generatedBy,
}) {
  const replaceInputRef = useRef(null)
  const badge = REQUIREMENT_BADGE[requirementType] || REQUIREMENT_BADGE.optional
  const statusMeta = STATUS_META[status] || STATUS_META.not_started
  const StatusIcon = statusMeta.icon
  const isGenerated = requirementType === 'generated'

  return (
    <div className="document-card">
      <div className="document-card-head">
        <div className="document-card-title">
          <FileText size={18} aria-hidden="true" />
          <div>
            <strong>{title}</strong>
            {officialName && <span className="document-card-official">Official name: {officialName}</span>}
          </div>
        </div>
        <Badge variant={badge.variant}>{badge.label}</Badge>
      </div>

      {description && <p className="document-card-desc">{description}</p>}

      <div className="document-card-status">
        <StatusIcon size={15} aria-hidden="true" />
        <span>{statusMeta.label}</span>
      </div>

      {isGenerated ? (
        <div className="document-card-generated">
          <Sparkles size={15} aria-hidden="true" />
          <span>Generated by {generatedBy || 'American Business Formations'} no upload needed.</span>
        </div>
      ) : disabled ? (
        <div className="document-card-locked">
          <Lock size={15} aria-hidden="true" />
          <span>{disabledReason || 'Available once your account is created.'}</span>
        </div>
      ) : file ? (
        <div className="document-card-file">
          <FileCheck2 size={16} aria-hidden="true" />
          <span className="document-card-filename">{file.name}</span>
          {file.size != null && <span className="document-card-filesize">{formatSize(file.size)}</span>}
          <div className="document-card-file-actions">
            <input ref={replaceInputRef} type="file" className="sr-only" onChange={e => { const f = e.target.files?.[0]; e.target.value = ''; if (f) onUpload?.(f) }} />
            <button type="button" className="btn btn-ghost btn-sm" onClick={() => replaceInputRef.current?.click()} aria-label={`Replace ${title}`}><RefreshCw size={14} /> Replace</button>
            <button type="button" className="btn btn-ghost btn-sm document-card-remove" onClick={() => onRemove?.()} aria-label={`Remove ${title}`}><Trash2 size={14} /> Remove</button>
          </div>
        </div>
      ) : (
        <FileDropzone
          id={`doc-${title.replace(/\s+/g, '-').toLowerCase()}`}
          label={`Upload ${title}`}
          maxSizeMb={maxSizeMb}
          uploading={uploading}
          progress={progress}
          error={uploadError}
          onFile={onUpload}
        />
      )}
    </div>
  )
}
